// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/welcome","name":"welcome","icon":"smile","parentId":"ant-design-pro-layout","id":"3"},"4":{"path":"/user-info","name":"用户信息","icon":"bug","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","redirect":"/admin/sub-page","parentId":"5","id":"6"},"7":{"path":"/admin/sub-page","name":"sub-page","parentId":"5","id":"7"},"8":{"name":"list.table-list","icon":"table","path":"/list","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/AI/calendar","icon":"calendar","name":"日程管理","parentId":"ant-design-pro-layout","id":"9"},"10":{"path":"/AI","name":"AI","icon":"robot","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/AI/document-writer","name":"AI 公文生成器","parentId":"10","id":"11"},"12":{"path":"/AI/translator","name":"AI 翻译","parentId":"10","id":"12"},"13":{"path":"/AI/meeting-assistant","name":"AI 会议助手","parentId":"10","id":"13"},"14":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"14"},"15":{"layout":false,"path":"./*","id":"15"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__user__login__index" */'@/pages/user/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__UserInfo__index" */'@/pages/UserInfo/index.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__table-list__index" */'@/pages/table-list/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__AI__Calendar__index" */'@/pages/AI/Calendar/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__AI__DocumentWriter__index" */'@/pages/AI/DocumentWriter/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__AI__Translator__index" */'@/pages/AI/Translator/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__AI__MeetingAssistant__index" */'@/pages/AI/MeetingAssistant/index.tsx')),
'14': React.lazy(() => import('./EmptyRoute')),
'15': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
