// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import BugOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BugOutlined';
import CrownOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TableOutlined';
import CalendarOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
import RobotOutlined from 'C:/Users/ddj/Desktop/DocumentWriter/DocumentWriter/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RobotOutlined';
export default { SmileOutlined, BugOutlined, CrownOutlined, TableOutlined, CalendarOutlined, RobotOutlined };
